baseURL: https://thenomadbits.com
languageCode: en-us
title: TheNomadBits
theme: [ "PaperMod", "shortcode-gallery" ]


params:
    homeInfoParams:
        Title: Hello, I'm Mansoor
        Content: Welcome to my travel blog. This is the place where I am supposed to write about my travel stories

    socialIcons:
        - name: instagram
          url: "https://instagram.com/_mansoormajeed"
        - name: youtube
          url: "https://www.youtube.com/channel/UCFt_y_F4gGTwSOoM5TOyBcQ"
        - name: github
          url: "https://github.com/MansoorMajeed"
    ShowBreadCrumbs: true
  
menu:
  main:
  - identifier: photography
    name: photography
    url: /photography/
    weight: 10
  - identifier: tech
    name: tech
    url: https://esc.sh
    weight: 10
  - identifier: about
    name: about
    url: https://esc.sh/about/
    weight: 15